# Generated by Django 4.2.5 on 2023-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxvehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxvehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
